# Nama workflow
name: Dart

# Event trigger untuk menjalankan workflow
on:
  push:
    branches: [ "main" ] # Jalankan saat ada push ke branch main
  pull_request:
    branches: [ "main" ] # Jalankan saat ada pull request ke branch main

# Job untuk membangun dan menjalankan tes
jobs:
  build:
    # Sistem operasi yang digunakan untuk menjalankan job
    runs-on: ubuntu-latest

    # Langkah-langkah dalam job
    steps:
      # Langkah pertama: Checkout kode dari repository
      - uses: actions/checkout@v4

      # Langkah kedua: Setup Dart SDK
      - uses: dart-lang/setup-dart@v1 # Menggunakan versi stabil terbaru Dart SDK

      # Langkah ketiga: Instal dependencies menggunakan `dart pub get`
      - name: Install dependencies
        run: dart pub get

      # Langkah keempat: Analyze kode menggunakan `dart analyze`
      - name: Analyze project source
        run: dart analyze

      # Langkah kelima: Jalankan tes menggunakan `dart test`
      - name: Run tests
        run: dart test
